- name: understanding variable preferences
  hosts: local
  connection: local
  vars:
    NAME: kumar
  vars_files:
  - files.yaml
  vars_prompt:
  - name: NAME
    promt: Please enter your name
    private: false
  tasks:
  - name: print the username
    vars: 
    NAME: Ramesh
    ansible.builtin.debug:
      msg: "{{ NAME }}"

